image: Visual Studio 2017

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: SanaraV2.sln

test_script:
- curl -LO https://download.rethinkdb.com/windows/rethinkdb-2.3.6.zip
- unzip rethinkdb-2.3.6.zip
- curl -LO http://www.commandline.co.uk/chp/chp-0.1.1.13.zip
- unzip chp-0.1.1.13.zip
- start chp/chp.exe rethinkdb-2.3.6/rethinkdb.exe
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\Sanara-UnitTests\bin\Debug\Sanara-UnitTests.dll -noshadow" -filter:"+[SanaraV2*]* -[SanaraV2*]*.Features.Tools.LinguistResources.*" -output:".\coverage.xml"
- codecov -f "coverage.xml"