image: Visual Studio 2017

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: SanaraV2.sln

test_script:
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\Sanara-UnitTests\bin\Debug\Sanara-UnitTests.dll -noshadow" -filter:"+[SanaraV2*]*.Features.* -[SanaraV2*]*.Features.Tools.LinguistResources.*" -output:".\coverage.xml"
- codecov -f "coverage.xml"